In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from 'C:\\Users\\hp\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [6]:
#create an array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,4,6,7])
a

array([1, 2, 4, 6, 7])

In [10]:
#to access an element in an array
a[2]
#remember it starts with 0

4

In [11]:
a[2] = 10
a

array([ 1,  2, 10,  6,  7])

In [12]:
#to a range up to 10
np.arange(10)312-391-68

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
#multi-dimensional arrays
np.zeros((5,2))
#rows first then columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
#array from a python list
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
n[0]
#remember they start with 0

array([1, 2, 3])

In [18]:
#to change or assign the last row
n[2] = [1,1,1]
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [20]:
#to select all rows and change 2nd column (again remember 0, 1, 2 to count)
n[:, 2] = [0, 1, 2]
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

In [21]:
#randomly generated arrays
np.random.rand(5,2)

array([[0.40556077, 0.28879213],
       [0.56127475, 0.95526184],
       [0.98608745, 0.25054052],
       [0.73165805, 0.42773387],
       [0.83811716, 0.28771819]])

In [22]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [23]:
#elements
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
a+1
#every element of this array changes - can do add, subtract, multiply, divide

array([1, 2, 3, 4, 5])

In [25]:
#change and save to a different array
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [26]:
#comparison 
a >= 2

array([False, False,  True,  True,  True])

In [27]:
#summarizing
a

array([0, 1, 2, 3, 4])

In [28]:
a.std()

1.4142135623730951

In [29]:
n.min()

0