In [1]:
import numpy as np

In [3]:
#vector operations
u = np.array([2,4,5,6])

In [4]:
2*u

array([ 4,  8, 10, 12])

In [5]:
v = np.array([1,0,0,2])

In [6]:
u + v

array([3, 4, 5, 8])

In [7]:
u * v

array([ 2,  0,  0, 12])

In [8]:
#multiplication
v.shape[0]

4

In [1]:
#write a function of vector to vector multiplication

def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [ ]:
#I stopped at this youtube video https://www.youtube.com/watch?v=zZyKUeOR4Gg&list=PL3MmuxUbc_hIhxl5Ji8t4O6lPAOpHaCLR&index=8&ab_channel=DataTalksClub at
#minute 8
#his github jupyter notebook is here https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/01-intro/notebooks/08-linear-algebra.ipynb